name: uztexpro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  local_auth: ^2.1.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  dropdown_search: ^5.0.2
  mobile_scanner: ^6.0.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/uztexpro.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/uztexpro.png
    - assets/images/uztexpro.png
  uses-material-design: true
